### ISSUE TITLE
[Feature] Add an option to disable cooldown.

### ISSUE THREAD

**Issue by maevius669** [MoriyaShiine/hearty-meals#5]
### Confirmations

- [X] I can verify that I am running the mod on the latest possible Minecraft version.
- [X] I can verify that the issue I am reporting exists on the latest possible Mod version.

### Mod version (NOT Minecraft version)

1.20-7

### A description of the issue

liek plz

### Log or crash report

not an issue tf

**Comment by MoriyaShiine** [comment]
1.20-7 is not the latest possible version. Issues are not meant for suggestions.

Besides, no. The cooldown is integral to the balance of the mod and would be horrendously overpowered without it
