### ISSUE TITLE
disableSprinting prevents swimming

### ISSUE THREAD

**Issue by anoomolu** [MoriyaShiine/hearty-meals#6]
### Confirmations

- [X] I can verify that I am running the mod on the latest possible Minecraft version.
- [X] I can verify that the issue I am reporting exists on the latest possible Mod version.

### Mod version (NOT Minecraft version)

1.21-r1

### A description of the issue

Hiya.

Firstly wanted to say thank you so much for this mod, it's fantastic and has features I've always liked playing with (Fabrication has a couple but won't be coming to 1.21, and I love the healing over time mechanic).

I noticed that the disableSprinting setting also disables swimming - I'm not sure if this is intentional or not. Fabrication also had an issue with this in the past, and needed a fix for disabling sprinting when exiting water onto land.

### Log or crash report

https://mclo.gs/XpuyQ6d

**Comment by MoriyaShiine** [comment]
Thank you for the kind words! Disabling sprinting does in fact also disable swimming and is intentional; it is there to emulate the feel of beta Minecraft, which did not have swimming either
